redis_url = "redis://localhost:6379/0"
extra_modules = ["examples.experimental.minimalist_demo.llm_colab_agents"]

[[nodes]]
node_name = "Jack"
node_class = "llm_agent"

[nodes.node_args]
query_interval = 6
output_channel = "Jack:Jane"
input_text_channels = ["Jane:Jack", "Scene:Jack"]
input_tick_channel = "tick/secs/1"
goal = "Wants to secretly marry Jane"
model_name = "gpt-4o-mini"
agent_name = "Jack"

[[nodes]]
node_name = "Jane"
node_class = "llm_agent"

[nodes.node_args]
query_interval = 7
output_channel = "Jane:Jack"
input_text_channels = ["Jack:Jane", "Scene:Jane"]
input_tick_channel = "tick/secs/1"
goal = "Wants to go to paris with Jake"
model_name = "gpt-4o-mini"
agent_name = "Jane"

[[nodes]]
node_name = "record"
node_class = "record"

[nodes.node_args]
jsonl_file_path = "log.jsonl"

[nodes.node_args.record_channel_types]
"Jack:Jane" = "agent_action"
"Jane:Jack" = "agent_action"

[[nodes]]
node_name = "tick"
node_class = "tick"

[[nodes]]
node_name = "scenario_context"
node_class = "scenario_context"

[nodes.node_args]
input_tick_channel = "tick/secs/1"
output_channels = ["Scene:Jane", "Scene:Jack"]
env_scenario = "There are 2 agents: Jack and Jane. They are talking to each other. Each agent has a goal and they are trying to achieve that goal."

[[nodes]]
node_name = "print"
node_class = "print"

[nodes.node_args.print_channel_types]
# "tick/secs/1" = "tick"
"Jane:Jack" = "agent_action"
"Jack:Jane" = "agent_action"
