redis_url = "redis://localhost:6379/0"
extra_modules = ["examples.experimental.realtime.realtime_websocket", "examples.experimental.realtime.input_node"]

[[nodes]]
node_name = "speaker"
node_class = "speaker"

[nodes.node_args]
rate = 24000
input_channel = "audio_output"


[[nodes]]
node_name = "listener"
node_class = "listener"

[nodes.node_args]
rate = 24000
output_channel = "audio_input"


[[nodes]]
node_name = "openai_realtime"
node_class = "openai_realtime"

[nodes.node_args]
input_channel = "audio_input"
output_channel = "audio_output"
