services:
  devcontainer:
    image: "ghcr.io/sotopia-lab/sotopia:latest"
    depends_on:
      ollama:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: "host"

  ollama:
    image: "ghcr.io/sotopia-lab/ollama:latest"
    ports:
      - 11434:11434
    container_name: ollama
    pull_policy: always
    restart: always
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis/redis-stack-server:7.2.0-v6
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data
    network_mode: "host"

networks:
  sotopia:
    external: false
volumes:
  redis_data:
