services:
  devcontainer:
    image: "ghcr.io/sotopia-lab/sotopia:latest"
    depends_on:
      llamacpp:
        condition: service_started
      redis:
        condition: service_healthy
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: "host"

  llamacpp:
    image: "ghcr.io/sotopia-lab/llamacpp:latest"
    container_name: llamacpp
    network_mode: "host"

  redis:
    image: redis/redis-stack-server:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data
    network_mode: "host"

networks:
  sotopia:
    external: false
volumes:
  redis_data:
