[project]
name = "socialstream"
version = "0.1.2"
description = "A UI for Sotopia."
authors = [
    { name = "Xuhui Zhou", email = "xuhuiz@cs.cmu.edu" },
    { name = "Su Zhe", email = "suz@cs.cmu.edu" }
]
requires-python = ">=3.10, <3.13"
license = { text = "MIT License" }
readme = "README.md"
