name: Pytest in docker

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  push:
    branches:
      - main
      - release
      - dev
  pull_request:
    branches:
      - main
      - release

jobs:
  Pytest:
    strategy:
      max-parallel: 5

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker
      if: runner.os == 'ubuntu-latest'
      uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12
    - name: Docker compose up
      run: |
        docker-compose -f .devcontainer/docker-compose.yml up -d
    - name: Test with pytest
      run: |
        docker compose -f .devcontainer/docker-compose.yml  run --rm -u root -v ./:/workspaces/sotopia devcontainer /bin/sh -c "export UV_PROJECT_ENVIRONMENT=/workspaces/.venv; cd /workspaces/sotopia; uv run --extra test --extra chat pytest --ignore tests/cli --cov=app --cov-report=xml"
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
