name: Pytest in docker

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  push:
    branches:
      - main
      - release
      - dev
  pull_request:
    branches:
      - main
      - release

jobs:
  Pytest:
    strategy:
      max-parallel: 5

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Tests
      uses: cloudposse/github-action-docker-compose-test-run@main
      with:
        file: .devcontainer/docker-compose.yml
        service: devcontainer
        registry: ghcr.io
        command: .github/workflows/tests.sh
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
